[tasks.watch]
workspace = false
command = "cargo"
args = ["watch", "-x", "run", "-w", "crates"]
env = { RUST_LOG = "o_log_n=info,aide=warn,axum=warn,tracing::span=warn" }

[tasks.docker-build]
workspace = false
command = "docker"
args = ["buildx", "build", "--platform=linux/amd64,linux/arm64", "-t", "movingju/public:o_log_n", "."]

[tasks.docker-push]
workspace = false
command = "docker"
args = ["push", "movingju/public:o_log_n"]
